---
title: Analisis Exploratorio de Datos
comments: true  # Activar comentarios
author: maicel monzon
date: '2025-02-11'
slug: eda
categories:
  - R
tags:
  - machine learnig
summary: Análisis Exploratorio de Datos implica el análisis de datos centrado en comprender los datos, identificar valores atípicos,  valores faltantes así como proporcionar la base para la formulación del modelo.
---

Análisis Exploratorio de Datos (EDA, por sus siglas en ingles) implica el análisis de datos centrado en comprender los datos, identificar valores atípicos,  valores faltantes así como proporcionar la base para la formulación del modelo. Además es importante conocer como se relacionan las variables.

Un concepto popular en el campo de la ciencia de datos llamado **GIGO** (Garbage in Garbage Out). Este concepto significa que los datos de mala calidad siempre producirán resultados deficientes, independientemente del modelo y la técnica utilizados. Acá te describo un flujo de trabajo que en mi opinión es muy practico, el orden de etapas y el cumplimiento depende del problema y no es una camisa de fuerza.



Este proceso incluye:

1. Compresión general de los datos y evaluación de su calidad

2. Identificación y tratamiento de valores faltantes y atípicos

3. Análisis de las distribución de las variables 

4. Análisis de las relaciones entre las variables

5. Transformación de los datos


